name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --name "JiraUSCreator" --icon=app.ico main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Jira US Creator ${{ github.ref_name }}
          files: dist/JiraUSCreator.exe
          draft: true
